name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Configure and Build Project
        uses: threeal/cmake-action@main

      - name: Binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-binary
          path: build/src/hello
          retention-days: 2
